name: Sample Workflow

on:
  push:
  workflow_dispatch:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: ステップA
        run: |
          echo "このコマンドは実行される"
          exit 0
          echo "このコマンドは実行されない（同じステップ内だから）"

      - name: ステップB
        run: echo "ステップAが成功したので、このステップは通常通り実行される"
