name: Test External Unpinned Composite Action

on:
  push:
  workflow_dispatch:

jobs:
  test-external-composite:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: tk3fftk/unpinned-composite-action@a43324f71d8149fd695f9b01da55f2bac6986c70 # v1
